# Use root/example as user/password credentials
version: '3.5'

services:

  bd:
    labels:
        projeto-whatsapp: "mysql"
    build: ./bd .
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    labels:
        projeto-whatsapp: "adminer"
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - bd
      
  api:
    labels:
        projeto-whatsapp: "api"
    build: ./api .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - bd
    environment:
        Logging__LogLevel__Default : "Information"
        ASPNETCORE_URLS: http://+:5000
        BD__TIPO: memoria
        #BD__SENHA: root
        #BD__USUARIO: root
        #BD__SERVIDOR: bd
        #BD__DATABASE: api